name: Run tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies (if any)
        run: |
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi

      - name: Run unit tests
        run: |
          if [ -d tests ]; then
            python -m unittest discover -s tests -v
          else
            echo "No tests directory found. Skipping."
          fi
